{{-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Report</title>
</head>
<body>
    <h3>Add new Report</h3>
    <form action="{{ url('/report/create') }}" method="post">
        @csrf
        <label for="period_start">Period End</label>
        <input type="date" name="period_start" id="">
        <br>
        <label for="period_end">Period End</label>
        <input type="date" name="period_end" id="">
        <br>
        <label for="report_type">Report Type</label>
        <input type="text" name="report_type" id="">
        <br>
        <label for="generated_by_user_id">Generated by</label>
        <input type="text" name="generated_by_user_id" id="">
        <br>
        <button type="submit">Add New Report</button>
        <br>
        <a href="{{ url('/report') }}">Go Back</a>
    </form>
</body>
</html> --}}
@extends('layouts.master')

@section('title', 'Add Report')

@section('page-title')
    <i class="bi bi-file-earmark-plus"></i> Add New Report
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('/report') }}">Reports</a></li>
                    <li class="breadcrumb-item active">Add New Report</li>
                </ol>
            </nav>

            <!-- Form Card -->
            <div class="card shadow">
                <div class="card-header bg-success text-white">
                    <h4 class="mb-0"><i class="bi bi-plus-circle"></i> Add New Report</h4>
                </div>
                <div class="card-body">
                    <form action="{{ url('/report/create') }}" method="POST">
                        @csrf
                        
                        <!-- Period Start -->
                        <div class="mb-3">
                            <label for="period_start" class="form-label">
                                Period Start <span class="text-danger">*</span>
                            </label>
                            <input type="date" 
                                   class="form-control" 
                                   id="period_start" 
                                   name="period_start" 
                                   required>
                        </div>

                        <!-- Period End -->
                        <div class="mb-3">
                            <label for="period_end" class="form-label">
                                Period End <span class="text-danger">*</span>
                            </label>
                            <input type="date" 
                                   class="form-control" 
                                   id="period_end" 
                                   name="period_end" 
                                   required>
                        </div>

                        <!-- Report Type -->
                        <div class="mb-3">
                            <label for="report_type" class="form-label">
                                Report Type <span class="text-danger">*</span>
                            </label>
                            <select class="form-select" id="report_type" name="report_type" required>
                                <option value="">Choose report type...</option>
                                <option value="sales">Sales Report</option>
                                <option value="inventory">Inventory Report</option>
                                <option value="financial">Financial Report</option>
                                <option value="customer">Customer Report</option>
                                <option value="product">Product Report</option>
                            </select>
                        </div>

                        <!-- Generated By User ID -->
                        <div class="mb-3">
                            <label for="generated_by_user_id" class="form-label">
                                Generated By (User ID) <span class="text-danger">*</span>
                            </label>
                            <input type="number" 
                                   class="form-control" 
                                   id="generated_by_user_id" 
                                   name="generated_by_user_id" 
                                   placeholder="Enter user ID" 
                                   min="1"
                                   required>
                            <small class="text-muted">Enter the ID of the user generating this report</small>
                        </div>

                        <!-- Buttons -->
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{{ url('/report') }}" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                            <button type="submit" class="btn btn-success">
                                <i class="bi bi-save"></i> Save Report
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection