<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Report</title>
</head>
<body>
    <h3>Add new Report</h3>
    <form action="{{ url('/report/create') }}" method="post">
        @csrf
        <label for="period_start">Period End</label>
        <input type="date" name="period_start" id="">
        <br>
        <label for="period_end">Period End</label>
        <input type="date" name="period_end" id="">
        <br>
        <label for="report_type">Report Type</label>
        <input type="text" name="report_type" id="">
        <br>
        <label for="generated_by_user_id">Generated by</label>
        <input type="text" name="generated_by_user_id" id="">
        <br>
        <button type="submit">Add New Report</button>
        <br>
        <a href="{{ url('/report') }}">Go Back</a>
    </form>
</body>
</html>