{{-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete Report</title>
</head>
<body>
    Are you sure you want to delete report No.<b>{{ $report_entry[0]->id }}</b>?
    <a href="{{ url('/report/'.$report_entry[0]->id.'/destroy') }}">Yes</a>
    <a href="{{ url('/report') }}">No</a>
</body>
</html> --}}
@extends('layouts.master')

@section('title', 'Delete Report')

@section('page-title')
    <i class="bi bi-trash"></i> Delete Report
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-6">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('/report') }}">Reports</a></li>
                    <li class="breadcrumb-item active">Delete Report</li>
                </ol>
            </nav>

            <!-- Delete Confirmation Card -->
            <div class="card shadow border-danger">
                <div class="card-header bg-danger text-white">
                    <h4 class="mb-0"><i class="bi bi-exclamation-triangle"></i> Confirm Deletion</h4>
                </div>
                <div class="card-body text-center">
                    <i class="bi bi-file-earmark-x text-danger" style="font-size: 4rem;"></i>
                    <h5 class="mt-3">Are you sure you want to delete this report?</h5>
                    
                    <!-- Report Details -->
                    <div class="alert alert-light mt-4 text-start">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <th width="40%">Report ID:</th>
                                <td><strong>#{{ $report_entry[0]->id }}</strong></td>
                            </tr>
                            <tr>
                                <th>Period Start:</th>
                                <td>{{ date('M d, Y', strtotime($report_entry[0]->period_start)) }}</td>
                            </tr>
                            <tr>
                                <th>Period End:</th>
                                <td>{{ date('M d, Y', strtotime($report_entry[0]->period_end)) }}</td>
                            </tr>
                            <tr>
                                <th>Report Type:</th>
                                <td><span class="badge bg-info">{{ ucfirst($report_entry[0]->report_type) }}</span></td>
                            </tr>
                            <tr>
                                <th>Generated By:</th>
                                <td>User #{{ $report_entry[0]->generated_by_user_id }}</td>
                            </tr>
                        </table>
                    </div>

                    <div class="alert alert-warning" role="alert">
                        <i class="bi bi-exclamation-circle"></i> 
                        <strong>Warning:</strong> This action cannot be undone!
                    </div>

                    <!-- Action Buttons -->
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-4">
                        <a href="{{ url('/report') }}" class="btn btn-secondary btn-lg">
                            <i class="bi bi-x-circle"></i> No, Go Back
                        </a>
                        <a href="{{ url('/report/'.$report_entry[0]->id.'/destroy') }}" class="btn btn-danger btn-lg">
                            <i class="bi bi-trash"></i> Yes, Delete Report
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection