{{-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Report</title>
</head>
<body>
    <h3>Edit Report</h3>
    <form action="{{ url('/report/'.$report_entry[0]->id.'/update') }}" method="post">
        @csrf
        <label for="period_start">Period End</label>
        <input type="date" name="period_start" id="" value="{{ $report_entry[0]->period_start }}">
        <br>
        <label for="period_end">Period End</label>
        <input type="date" name="period_end" id="" value="{{ $report_entry[0]->period_end }}">
        <br>
        <label for="report_type">Report Type</label>
        <input type="text" name="report_type" id="" value="{{ $report_entry[0]->report_type }}">
        <br>
        <label for="generated_by_user_id">Generated by</label>
        <input type="text" name="generated_by_user_id" id="" value="{{ $report_entry[0]->generated_by_user_id }}">
        <br>
        <button type="submit">Update Report</button>
        <br>
        <a href="{{ url('/report') }}">Go Back</a>
    </form>
</body>
</html> --}}
@extends('layouts.master')

@section('title', 'Edit Report')

@section('page-title')
    <i class="bi bi-pencil-square"></i> Edit Report
@endsection

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ url('/report') }}">Reports</a></li>
                    <li class="breadcrumb-item active">Edit Report</li>
                </ol>
            </nav>

            <!-- Form Card -->
            <div class="card shadow">
                <div class="card-header bg-warning">
                    <h4 class="mb-0"><i class="bi bi-pencil"></i> Edit Report</h4>
                </div>
                <div class="card-body">
                    <form action="{{ url('/report/'.$report_entry[0]->id.'/update') }}" method="POST">
                        @csrf
                        
                        <!-- Period Start -->
                        <div class="mb-3">
                            <label for="period_start" class="form-label">
                                Period Start <span class="text-danger">*</span>
                            </label>
                            <input type="date" 
                                   class="form-control" 
                                   id="period_start" 
                                   name="period_start" 
                                   value="{{ $report_entry[0]->period_start }}"
                                   required>
                        </div>

                        <!-- Period End -->
                        <div class="mb-3">
                            <label for="period_end" class="form-label">
                                Period End <span class="text-danger">*</span>
                            </label>
                            <input type="date" 
                                   class="form-control" 
                                   id="period_end" 
                                   name="period_end" 
                                   value="{{ $report_entry[0]->period_end }}"
                                   required>
                        </div>

                        <!-- Report Type -->
                        <div class="mb-3">
                            <label for="report_type" class="form-label">
                                Report Type <span class="text-danger">*</span>
                            </label>
                            <select class="form-select" id="report_type" name="report_type" required>
                                <option value="sales" {{ $report_entry[0]->report_type == 'sales' ? 'selected' : '' }}>Sales Report</option>
                                <option value="inventory" {{ $report_entry[0]->report_type == 'inventory' ? 'selected' : '' }}>Inventory Report</option>
                                <option value="financial" {{ $report_entry[0]->report_type == 'financial' ? 'selected' : '' }}>Financial Report</option>
                                <option value="customer" {{ $report_entry[0]->report_type == 'customer' ? 'selected' : '' }}>Customer Report</option>
                                <option value="product" {{ $report_entry[0]->report_type == 'product' ? 'selected' : '' }}>Product Report</option>
                            </select>
                        </div>

                        <!-- Generated By User ID -->
                        <div class="mb-3">
                            <label for="generated_by_user_id" class="form-label">
                                Generated By (User ID) <span class="text-danger">*</span>
                            </label>
                            <input type="number" 
                                   class="form-control" 
                                   id="generated_by_user_id" 
                                   name="generated_by_user_id" 
                                   value="{{ $report_entry[0]->generated_by_user_id }}"
                                   min="1"
                                   required>
                        </div>

                        <!-- Buttons -->
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{{ url('/report') }}" class="btn btn-secondary">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                            <button type="submit" class="btn btn-warning">
                                <i class="bi bi-save"></i> Update Report
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection