<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Report</title>
</head>
<body>
    <h3>Edit Report</h3>
    <form action="{{ url('/report/'.$report_entry[0]->id.'/update') }}" method="post">
        @csrf
        <label for="period_start">Period End</label>
        <input type="date" name="period_start" id="" value="{{ $report_entry[0]->period_start }}">
        <br>
        <label for="period_end">Period End</label>
        <input type="date" name="period_end" id="" value="{{ $report_entry[0]->period_end }}">
        <br>
        <label for="report_type">Report Type</label>
        <input type="text" name="report_type" id="" value="{{ $report_entry[0]->report_type }}">
        <br>
        <label for="generated_by_user_id">Generated by</label>
        <input type="text" name="generated_by_user_id" id="" value="{{ $report_entry[0]->generated_by_user_id }}">
        <br>
        <button type="submit">Update Report</button>
        <br>
        <a href="{{ url('/report') }}">Go Back</a>
    </form>
</body>
</html>