@extends('layouts.master')

@section('title', 'Reports Management')

@section('page-title')
    <i class="bi bi-file-earmark-bar-graph"></i> Reports Management
@endsection

@section('content')
    <!-- Add Button -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <p class="text-muted mb-0">Generate and manage system reports</p>
        </div>
        <a href="{{ url('/report/add') }}" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New Report
        </a>
    </div>

    <!-- Reports Table Card -->
    <div class="card shadow">
        <div class="card-header bg-white">
            <h5 class="mb-0"><i class="bi bi-table"></i> Reports List</h5>
        </div>
        <div class="card-body">
            @if (empty($report_list) || count($report_list) == 0)
                <div class="alert alert-info text-center" role="alert">
                    <i class="bi bi-info-circle"></i> There are no reports in the database yet.
                    <br>
                    <a href="{{ url('/report/add') }}" class="btn btn-primary mt-2">
                        Add Your First Report
                    </a>
                </div>
            @else
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead class="table-dark">
                            <tr>
                                <th>ID</th>
                                <th>Period Start</th>
                                <th>Period End</th>
                                <th>Report Type</th>
                                <th>Generated By</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($report_list as $reports)
                                <tr>
                                    <td>
                                        <span class="badge bg-primary">#{{ $reports->id }}</span>
                                    </td>
                                    <td>
                                        <i class="bi bi-calendar-check"></i> 
                                        {{ date('M d, Y', strtotime($reports->period_start)) }}
                                    </td>
                                    <td>
                                        <i class="bi bi-calendar-x"></i> 
                                        {{ date('M d, Y', strtotime($reports->period_end)) }}
                                    </td>
                                    <td>
                                        <span class="badge bg-info">{{ ucfirst($reports->report_type) }}</span>
                                    </td>
                                    <td>
                                        <span class="badge bg-secondary">
                                            <i class="bi bi-person"></i> User #{{ $reports->generated_by_user_id }}
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        <div class="btn-group" role="group">
                                            <a href="{{ url('/report/'.$reports->id.'/edit') }}" 
                                               class="btn btn-sm btn-warning" 
                                               title="Edit">
                                                <i class="bi bi-pencil"></i> Edit
                                            </a>
                                            <a href="{{ url('/report/'.$reports->id.'/delete') }}" 
                                               class="btn btn-sm btn-danger" 
                                               title="Delete">
                                                <i class="bi bi-trash"></i> Delete
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    </div>
@endsection